# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 399b9687af94b0caef9ded06ea06f4347ad6e439aa5ad8237297a20f50651ef8b006c16c6b6081d01a4fcd881a691b78dc53c0c7af2d135a330159dd547f0ef5

test:
  secret_key_base: 238d8de9b6dc31345bd0e2150efe03da1b8293fab63508f80fc4a5fed5899149812773a421f26425d18d63acc3ab00a1e780f09caa647651fdb655b44db7063e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
